import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent

LLM_MODE = os.getenv("MUSIC_AGENT_LLM_MODE", "mock").strip().lower()
if LLM_MODE not in {"mock", "qwen"}:
    LLM_MODE = "mock"

LLM_TIMEOUT = int(os.getenv("MUSIC_AGENT_LLM_TIMEOUT", "30"))
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY", os.getenv("DASHSCOPE_API_KEY_BAILIAN", ""))

DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = DATA_DIR / "models"
PROCESSED_DIR = DATA_DIR / "processed"
INDEX_DIR = PROJECT_ROOT / "index" / "chroma_bge_m3"
DATASET_DIR = PROJECT_ROOT / "dataset"
AUDIO_DIR = DATASET_DIR / "raw" / "fma_small"

ORCHESTRATOR_MAX_TOOL_CALLS = 3
ORCHESTRATOR_MAX_HISTORY_TURNS = 5
ORCHESTRATOR_RAG_MAX_CHARS = 1200
ORCHESTRATOR_RAG_TOP_K = 5
ORCHESTRATOR_TOOL_RESULTS_TOP_K = 5
ORCHESTRATOR_TOOL_RESULTS_MAX_SOURCES = 3
ORCHESTRATOR_ENABLE_LLM_INTENT = True
ORCHESTRATOR_ENABLE_PREFERENCE = True
ORCHESTRATOR_DEMO_MODE = True
ORCHESTRATOR_CANDIDATE_MULTIPLIER = 8

DISPLAY_SCORE_MIN = 65
DISPLAY_SCORE_MAX = 98
DISPLAY_SCORE_TOP = 95
DISPLAY_SCORE_BOTTOM = 75

RECOMMEND_TOP_K_DEFAULT = 5
RECOMMEND_TOP_K_MIN = 1
RECOMMEND_TOP_K_MAX = 20
RECOMMEND_CF_TOP_K = 3
RECOMMEND_EXCLUDE_IDS_CAP = 100

RAG_RETRIEVAL_TOP_K = 5
RAG_CONTEXT_MAX_CHARS = 1200

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
